#!/usr/bin/env node
var fs = require('fs');

try {
  fs.readFileSync('.env', 'utf8');
}
catch(e) {
  const currentEnv = fs.readFileSync('.env.sample', 'utf8');
  fs.writeFileSync('.env', currentEnv, 'utf8');
}