#!/usr/bin/env node

var childProcess = require('child_process')
var connstring = ' -h 127.0.0.1 -p 5432 -U postgres -w '

console.log("Installing PostgreSQL...")
childProcess.execSync('docker-compose kill db')
childProcess.execSync('docker-compose rm -f db')
childProcess.execSync('docker-compose up -d db')

setTimeout(function() {
    try {
        childProcess.execSync('dropdb'+connstring+'ground_control')
    } catch (ex) {
        console.warn("dropdb did not run. This is probably because the database does not already exist, which is fine.")
    }
    try {
        childProcess.execSync('createdb'+connstring+'ground_control')
    } catch(ex) {
        console.warn("createdb did not run. This is probably because the database already exists, which is fine.");
    }
    try {
        childProcess.execSync('psql'+connstring+' -c "CREATE ROLE ground_control WITH LOGIN SUPERUSER;" -d ground_control')
    } catch (ex) {
        console.warn("ground_control role not created.  This is probably because the role already exists, which is fine.");
    }

    console.log("Seeding data...")
    childProcess.execSync('npm run seed');
    console.log("Done!")
}, 20000)
