#!/usr/bin/env node

var childProcess = require('child_process')
console.log("Installing PostgreSQL...")
childProcess.execSync('brew install postgres')

console.log("Installing Postgis...")
childProcess.execSync('brew install postgis')

console.log("Starting up database...")
childProcess.exec('postgres -D /usr/local/var/postgres')

setTimeout(function() {
    try {
        childProcess.execSync('dropdb ground_control')
    } catch (ex) {
        console.log("dropdb did not run. This is probably because the database does not already exist, which is fine.")
    }
    try {
        childProcess.execSync('createdb ground_control')
    } catch(ex) {
        console.log("createdb did not run. This is probably because the database already exists, which is fine.");
    }
    try {
        childProcess.execSync('psql -c "CREATE ROLE ground_control WITH LOGIN SUPERUSER;" -d ground_control')
    } catch (ex) {
        console.log("ground_control role not created.  This is probably because the role already exists, which is fine.");
    }

    try {
        childProcess.execSync('psql -c "create extension postgis" -d ground_control')
    } catch (ex) {
        console.log("PostGIS already installed")
    }

    console.log("Seeding data...")
    childProcess.execSync('npm run migrate');
    childProcess.execSync('npm run seed');
    console.log("Done!")
}, 2000)
